[project]
name = "skindisease"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-rest-framework>=0.1.0",
    "environs>=14.5.0",
    "pillow>=12.0.0",
    "psycopg2>=2.9.11",
    "ruff>=0.14.3",
]
